services:
  web:
    image: node:alpine
    command: npm start
    working_dir: /usr/web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/web
    links:
      - api
    depends_on:
      - api
  api:
    image: node:alpine
    command: npm run dev
    working_dir: /usr/api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/api
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017